{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "c429c26c-344f-44b2-b92d-ec16eb396e68",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "1. Cluster: 'rt theredsindo' (total: 11 tweet)\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Daftar kapten Liverpool saat memenangi gelar Liga Inggris:\n",
      "\n",
      "🏴󠁧󠁢󠁳󠁣󠁴󠁿 Alex Raisbeck (1900-01, 1905-06)\n",
      "🏴󠁧󠁢󠁳󠁣󠁴󠁿 Donald Macki…\n",
      " - RT @The_RedsIndo: Tim Big 5 dan kapan mereka terakhir juara Liga Inggris\n",
      "\n",
      "• Liverpool: 2025\n",
      "• Man City: 2024\n",
      "• Chelsea: 2017\n",
      "• Man United:…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Daftar kapten Liverpool saat memenangi gelar Liga Inggris:\n",
      "\n",
      "🏴󠁧󠁢󠁳󠁣󠁴󠁿 Alex Raisbeck (1900-01, 1905-06)\n",
      "🏴󠁧󠁢󠁳󠁣󠁴󠁿 Donald Macki…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      "\n",
      "2. Cluster: 'theredsindo gary' (total: 8 tweet)\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      "\n",
      "3. Cluster: 'gary neville' (total: 8 tweet)\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      "\n",
      "4. Cluster: 'neville menegaskan' (total: 8 tweet)\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      "\n",
      "5. Cluster: 'menegaskan liverpool' (total: 8 tweet)\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      "\n",
      "6. Cluster: 'liverpool klub' (total: 8 tweet)\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      "\n",
      "7. Cluster: 'klub terbesar' (total: 8 tweet)\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      "\n",
      "8. Cluster: 'terbesar inggris' (total: 8 tweet)\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      "\n",
      "9. Cluster: 'inggris neville' (total: 8 tweet)\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      "\n",
      "10. Cluster: 'neville liverpool' (total: 8 tweet)\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      "\n",
      "11. Cluster: 'liverpool memiliki' (total: 8 tweet)\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      "\n",
      "12. Cluster: 'memiliki lebih' (total: 8 tweet)\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      "\n",
      "13. Cluster: 'lebih banyak' (total: 8 tweet)\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      "\n",
      "14. Cluster: 'banyak piala' (total: 8 tweet)\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      "\n",
      "15. Cluster: 'rt theredsindo gary' (total: 8 tweet)\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      "\n",
      "16. Cluster: 'theredsindo gary neville' (total: 8 tweet)\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      "\n",
      "17. Cluster: 'gary neville menegaskan' (total: 8 tweet)\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      "\n",
      "18. Cluster: 'neville menegaskan liverpool' (total: 8 tweet)\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      "\n",
      "19. Cluster: 'menegaskan liverpool klub' (total: 8 tweet)\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      "\n",
      "20. Cluster: 'liverpool klub terbesar' (total: 8 tweet)\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      "\n",
      "21. Cluster: 'klub terbesar inggris' (total: 8 tweet)\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      "\n",
      "22. Cluster: 'terbesar inggris neville' (total: 8 tweet)\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      "\n",
      "23. Cluster: 'inggris neville liverpool' (total: 8 tweet)\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      "\n",
      "24. Cluster: 'neville liverpool memiliki' (total: 8 tweet)\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      "\n",
      "25. Cluster: 'liverpool memiliki lebih' (total: 8 tweet)\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      "\n",
      "26. Cluster: 'memiliki lebih banyak' (total: 8 tweet)\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      "\n",
      "27. Cluster: 'lebih banyak piala' (total: 8 tweet)\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      "\n",
      "28. Cluster: 'rt theredsindo gary neville' (total: 8 tweet)\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      "\n",
      "29. Cluster: 'theredsindo gary neville menegaskan' (total: 8 tweet)\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      "\n",
      "30. Cluster: 'gary neville menegaskan liverpool' (total: 8 tweet)\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      "\n",
      "31. Cluster: 'neville menegaskan liverpool klub' (total: 8 tweet)\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      "\n",
      "32. Cluster: 'menegaskan liverpool klub terbesar' (total: 8 tweet)\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      "\n",
      "33. Cluster: 'liverpool klub terbesar inggris' (total: 8 tweet)\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      "\n",
      "34. Cluster: 'klub terbesar inggris neville' (total: 8 tweet)\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      "\n",
      "35. Cluster: 'terbesar inggris neville liverpool' (total: 8 tweet)\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      "\n",
      "36. Cluster: 'inggris neville liverpool memiliki' (total: 8 tweet)\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      "\n",
      "37. Cluster: 'neville liverpool memiliki lebih' (total: 8 tweet)\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      "\n",
      "38. Cluster: 'liverpool memiliki lebih banyak' (total: 8 tweet)\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      "\n",
      "39. Cluster: 'memiliki lebih banyak piala' (total: 8 tweet)\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      " - RT @The_RedsIndo: Gary Neville menegaskan bahwa Liverpool adalah klub terbesar di Inggris.\n",
      "\n",
      "Neville: \"Liverpool memiliki lebih banyak Piala…\n",
      "\n",
      "40. Cluster: 'liga inggris' (total: 34 tweet)\n",
      " - @pretendto068 @The_RedsIndo Arsenal secara tropi aja terbanyak ketiga setelah Liverpool &amp; MU, dilihat dari tropi liga Inggris juga Arsenal nomor 3, jadi tim mana yg ngga layak?\n",
      " - RT @The_RedsIndo: Daftar kapten Liverpool saat memenangi gelar Liga Inggris:\n",
      "\n",
      "🏴󠁧󠁢󠁳󠁣󠁴󠁿 Alex Raisbeck (1900-01, 1905-06)\n",
      "🏴󠁧󠁢󠁳󠁣󠁴󠁿 Donald Macki…\n",
      " - RT @lupa_mancing: Mentari menyapa juara liga inggris. Scouse is not england. Kepalkan tanganmu kawand✊✊. Sampai menang.\n",
      "#YNWA #aaauuuwww ht…\n",
      " - Liverpool Kunci Juara Liga Inggris usai Hajar Tottenham Hotspur 5-1\n",
      "\n",
      "Cakeeeppp\n",
      " - RT @txtdrkeylie: mau 13 epl kek, 2 epl kek. itungan secara keseluruhannya ttp GELAR LIGA INGGRIS. fans emyu jgn berisik dah kocak, mending…\n",
      " - @ppnnooxx @AlfnGnrs @aldibawazier_ lah postingan lain beda konteks lah pea, selain baper, fans mu gak bisa ngecerna tulisan ya alias minim literasi....makanya stop bahas sejarah biar gak baper dan stress, btw Selamat liverpool udah menang 20 trofi liga Inggris\n",
      " - @ppnnooxx @AlfnGnrs @aldibawazier_ nah coba lo baca lagi postingan aldi, ada bawa bawa MU? soalnya setau aku format liga inggris emang berubah sejak tahun 92.... Kebanyakan bahas sejarah jadinya baperan njir\n",
      " - RT @utdfocusid: Pejamkan mata lalu nikmati detik-detik terakhir kita sebagai penguasa Liga Inggris dengan 20 gelar juaranya.\n",
      "\n",
      "Sebentar lagi…\n",
      " - @notfakboyyy @liskiataumi @idextratime @footballontnt musim ini enggak sih\n",
      "dari 12 tim yang masih main di kompetisi eropa 4 dari liga inggris\n",
      "dan musim depan ada kemungkinan inggris punya 6 wakil di liga champions kalau MU/Spurs juara europa\n",
      " - RT @The_RedsIndo: Daftar kapten Liverpool saat memenangi gelar Liga Inggris:\n",
      "\n",
      "🏴󠁧󠁢󠁳󠁣󠁴󠁿 Alex Raisbeck (1900-01, 1905-06)\n",
      "🏴󠁧󠁢󠁳󠁣󠁴󠁿 Donald Macki…\n",
      " - @idextratime @footballontnt predikat liga terbaik sih masih bisa diperdebatkan. tapi yang pasti liga inggris ini liga terseru untuk diikuti. apalagi jam tayangnya bersahabat untuk asia. kalau nonton liga lain gak tau kenapa bawaannya bosen ditonton.\n",
      " - RT @panditfootball: Wataru Endo jadi samurai keempat yang juara Liga Inggris 🇯🇵\n",
      "\n",
      "Siapa lagi pemain Jepang yang bakal juara di Inggris? 🤔 ht…\n",
      " - Liverpool Patahkan Prediksi Tak Dijagokan Juara Liga Inggris 2024/2025 https://t.co/IRptZXDsD4\n",
      " - @TohhirRadin @LaunchSatelite @liskiataumi @idextratime @footballontnt Prestasi juara liga champion atau Europa, kalo dilihat banyak tim liga Inggris ko yang juara dibanding liga2 lain contoh Spain yang juara champions paling madrid barca liga Inggris nothingham sama Aston aja pernah\n",
      " - RT @BetaKopites: Dulu, pernah jadi lawan di Liga Belanda. \n",
      "\n",
      "Sekarang, jadi satu tim dan Juara bersama di Liga Inggris. \n",
      "\n",
      "Arne Slot 🤝 Virgil…\n",
      " - Mentari menyapa juara liga inggris. Scouse is not england. Kepalkan tanganmu kawand✊✊. Sampai menang.\n",
      "#YNWA #aaauuuwww https://t.co/Jtku5yAdv3\n",
      " - RT @hariankompas: Liga Inggris musim 2024-2025 adalah pembuktian Liverpool sebagai tim perkasa meskipun awalnya dipandang sebelah mata. Mus…\n",
      " - @friginiawan @FabrizioRomano @VidioSports Ente kalo langganan mola atau vision+ apa gak kejang-kejang 😅\n",
      "\n",
      "Ini yg provide liga 1, Liga Inggris yg grafiknya gede, bisa lancar jaya aja masih dibacotin\n",
      " - RT @deMan45567577: @aldibawazier_ Yg jelas, Divisi Utama Liga Inggris ada sejak 1888\n",
      "\n",
      "Khusus Liverpool, gelar juara liga mereka sebagian be…\n",
      " - RT @idextratime: ✅ RESMI : Arsenal kembali kalah tipis dalam perebutan gelar juara Liga Inggris.\n",
      "\n",
      "2023 : Runner-up \n",
      "2024 : Runner-up \n",
      "2025…\n",
      " - RT @txtdrkeylie: mau 13 epl kek, 2 epl kek. itungan secara keseluruhannya ttp GELAR LIGA INGGRIS. fans emyu jgn berisik dah kocak, mending…\n",
      " - @mitosbola mantps liverpool juara liga inggris🔥\n",
      " - RT @panditfootball: Wataru Endo jadi samurai keempat yang juara Liga Inggris 🇯🇵\n",
      "\n",
      "Siapa lagi pemain Jepang yang bakal juara di Inggris? 🤔 ht…\n",
      " - RT @The_RedsIndo: Tim Big 5 dan kapan mereka terakhir juara Liga Inggris\n",
      "\n",
      "• Liverpool: 2025\n",
      "• Man City: 2024\n",
      "• Chelsea: 2017\n",
      "• Man United:…\n",
      " - RT @mitosbola: Liverpool Berpeluang Pecahkan Rekor Selisih Poin Terbesar Liga Inggris\n",
      "\n",
      "U-kiss #HQ_AGZEPS147 #HANDSUP_BY_MEOVV\n",
      "\n",
      "https://t.co…\n",
      " - RT @BetaKopites: Pemain Liverpool musim ini yang statusnya sudah dapet 2 gelar Liga Inggris:\n",
      "\n",
      "TAA\n",
      "Alisson\n",
      "CURTIS JONES\n",
      "Joe Gomez\n",
      "Mohamed Sa…\n",
      " - @utdfocusid Belegug, ngitung jumlah titel juara liga Inggris selalu dari perubahan nama liga. ...siga bolon wae😅\n",
      " - RT @arsenalskitchen: Selamat, Liverpool. Juara Liga Inggris 2024/2025.\n",
      "\n",
      "Konsisten itu selalu krusial. Liverpool yg paling punya aspek itu s…\n",
      " - RT @LFCIndonesia: 2⃣0⃣ x Liga Inggris\n",
      "6⃣ x Liga Champions UEFA\n",
      "8⃣ x Piala FA\n",
      "3⃣ x Liga Eropa UEFA\n",
      "🔟 x Piala Liga\n",
      "4⃣ x Piala Super UEFA\n",
      "1⃣ x…\n",
      " - @atwin @FabrizioRomano @VidioSports Siapa yang sanggup bayarin hak siar liga inggris?\n",
      " - RT @idextratime: ✅ RESMI : Arne Slot mencatatkan sejarah sebagai pelatih PERTAMA Liverpool yang meraih gelar Liga Inggris pada MUSIM PERDAN…\n",
      " - @idextratime @footballontnt Liga inggris media nya bagus dan liga nya di kelola dengan cara terbaik di dunia\n",
      "\n",
      "Ya meski tidak berimpact signifikan terhadap timnas nya, tetapi liga inggris terbaik dari pengelolaan dan penggunaan media\n",
      " - @liskiataumi @idextratime @footballontnt Kalo gua ambil kesimpulan dari kata2 lu berarti liga Inggris nih liga Entertainment dong, secara prestasi di Eropa pun masih ada liga2 lain yg lebih baik faktanya\n",
      " - RT @FaktaSepakbola: RESMI: Liverpool kini ikut jadi tim dengan jumlah trofi Liga Inggris terbanyak sepanjang sejarah (20 trofi). 👏\n",
      "\n",
      "Menyama…\n",
      "\n",
      "41. Cluster: 'gelar liga' (total: 6 tweet)\n",
      " - RT @The_RedsIndo: Daftar kapten Liverpool saat memenangi gelar Liga Inggris:\n",
      "\n",
      "🏴󠁧󠁢󠁳󠁣󠁴󠁿 Alex Raisbeck (1900-01, 1905-06)\n",
      "🏴󠁧󠁢󠁳󠁣󠁴󠁿 Donald Macki…\n",
      " - RT @BetaKopites: Pemain Liverpool musim ini yang statusnya sudah dapet 2 gelar Liga Inggris:\n",
      "\n",
      "TAA\n",
      "Alisson\n",
      "CURTIS JONES\n",
      "Joe Gomez\n",
      "Mohamed Sa…\n",
      " - RT @txtdrkeylie: mau 13 epl kek, 2 epl kek. itungan secara keseluruhannya ttp GELAR LIGA INGGRIS. fans emyu jgn berisik dah kocak, mending…\n",
      " - RT @idextratime: ✅ RESMI : Arne Slot mencatatkan sejarah sebagai pelatih PERTAMA Liverpool yang meraih gelar Liga Inggris pada MUSIM PERDAN…\n",
      " - RT @The_RedsIndo: Daftar kapten Liverpool saat memenangi gelar Liga Inggris:\n",
      "\n",
      "🏴󠁧󠁢󠁳󠁣󠁴󠁿 Alex Raisbeck (1900-01, 1905-06)\n",
      "🏴󠁧󠁢󠁳󠁣󠁴󠁿 Donald Macki…\n",
      " - RT @txtdrkeylie: mau 13 epl kek, 2 epl kek. itungan secara keseluruhannya ttp GELAR LIGA INGGRIS. fans emyu jgn berisik dah kocak, mending…\n",
      "\n",
      "42. Cluster: 'gelar liga inggris' (total: 6 tweet)\n",
      " - RT @The_RedsIndo: Daftar kapten Liverpool saat memenangi gelar Liga Inggris:\n",
      "\n",
      "🏴󠁧󠁢󠁳󠁣󠁴󠁿 Alex Raisbeck (1900-01, 1905-06)\n",
      "🏴󠁧󠁢󠁳󠁣󠁴󠁿 Donald Macki…\n",
      " - RT @BetaKopites: Pemain Liverpool musim ini yang statusnya sudah dapet 2 gelar Liga Inggris:\n",
      "\n",
      "TAA\n",
      "Alisson\n",
      "CURTIS JONES\n",
      "Joe Gomez\n",
      "Mohamed Sa…\n",
      " - RT @txtdrkeylie: mau 13 epl kek, 2 epl kek. itungan secara keseluruhannya ttp GELAR LIGA INGGRIS. fans emyu jgn berisik dah kocak, mending…\n",
      " - RT @idextratime: ✅ RESMI : Arne Slot mencatatkan sejarah sebagai pelatih PERTAMA Liverpool yang meraih gelar Liga Inggris pada MUSIM PERDAN…\n",
      " - RT @The_RedsIndo: Daftar kapten Liverpool saat memenangi gelar Liga Inggris:\n",
      "\n",
      "🏴󠁧󠁢󠁳󠁣󠁴󠁿 Alex Raisbeck (1900-01, 1905-06)\n",
      "🏴󠁧󠁢󠁳󠁣󠁴󠁿 Donald Macki…\n",
      " - RT @txtdrkeylie: mau 13 epl kek, 2 epl kek. itungan secara keseluruhannya ttp GELAR LIGA INGGRIS. fans emyu jgn berisik dah kocak, mending…\n",
      "\n",
      "43. Cluster: 'juara liga' (total: 14 tweet)\n",
      " - @mitosbola mantps liverpool juara liga inggris🔥\n",
      " - RT @panditfootball: Wataru Endo jadi samurai keempat yang juara Liga Inggris 🇯🇵\n",
      "\n",
      "Siapa lagi pemain Jepang yang bakal juara di Inggris? 🤔 ht…\n",
      " - RT @The_RedsIndo: Tim Big 5 dan kapan mereka terakhir juara Liga Inggris\n",
      "\n",
      "• Liverpool: 2025\n",
      "• Man City: 2024\n",
      "• Chelsea: 2017\n",
      "• Man United:…\n",
      " - @The_RedsIndo Kan emang 20.. yg blg 2 siapa? Klo d format EPL mmg 2.. klo total juara Liga utama Inggris y 20.. gmn dah? Kan mmg sama dgn MU 20 juara.. biasa itu.. dulu pas MU masih 7 gelar trus nyamain jd 18 apakah seberisik ini jg?\n",
      " - RT @lupa_mancing: Mentari menyapa juara liga inggris. Scouse is not england. Kepalkan tanganmu kawand✊✊. Sampai menang.\n",
      "#YNWA #aaauuuwww ht…\n",
      " - @utdfocusid Belegug, ngitung jumlah titel juara liga Inggris selalu dari perubahan nama liga. ...siga bolon wae😅\n",
      " - Liverpool Kunci Juara Liga Inggris usai Hajar Tottenham Hotspur 5-1\n",
      "\n",
      "Cakeeeppp\n",
      " - RT @arsenalskitchen: Selamat, Liverpool. Juara Liga Inggris 2024/2025.\n",
      "\n",
      "Konsisten itu selalu krusial. Liverpool yg paling punya aspek itu s…\n",
      " - RT @panditfootball: Wataru Endo jadi samurai keempat yang juara Liga Inggris 🇯🇵\n",
      "\n",
      "Siapa lagi pemain Jepang yang bakal juara di Inggris? 🤔 ht…\n",
      " - Liverpool Patahkan Prediksi Tak Dijagokan Juara Liga Inggris 2024/2025 https://t.co/IRptZXDsD4\n",
      " - @TohhirRadin @LaunchSatelite @liskiataumi @idextratime @footballontnt Prestasi juara liga champion atau Europa, kalo dilihat banyak tim liga Inggris ko yang juara dibanding liga2 lain contoh Spain yang juara champions paling madrid barca liga Inggris nothingham sama Aston aja pernah\n",
      " - Mentari menyapa juara liga inggris. Scouse is not england. Kepalkan tanganmu kawand✊✊. Sampai menang.\n",
      "#YNWA #aaauuuwww https://t.co/Jtku5yAdv3\n",
      " - RT @deMan45567577: @aldibawazier_ Yg jelas, Divisi Utama Liga Inggris ada sejak 1888\n",
      "\n",
      "Khusus Liverpool, gelar juara liga mereka sebagian be…\n",
      " - RT @idextratime: ✅ RESMI : Arsenal kembali kalah tipis dalam perebutan gelar juara Liga Inggris.\n",
      "\n",
      "2023 : Runner-up \n",
      "2024 : Runner-up \n",
      "2025…\n",
      "\n",
      "44. Cluster: 'juara liga inggris' (total: 11 tweet)\n",
      " - @mitosbola mantps liverpool juara liga inggris🔥\n",
      " - RT @panditfootball: Wataru Endo jadi samurai keempat yang juara Liga Inggris 🇯🇵\n",
      "\n",
      "Siapa lagi pemain Jepang yang bakal juara di Inggris? 🤔 ht…\n",
      " - RT @The_RedsIndo: Tim Big 5 dan kapan mereka terakhir juara Liga Inggris\n",
      "\n",
      "• Liverpool: 2025\n",
      "• Man City: 2024\n",
      "• Chelsea: 2017\n",
      "• Man United:…\n",
      " - RT @lupa_mancing: Mentari menyapa juara liga inggris. Scouse is not england. Kepalkan tanganmu kawand✊✊. Sampai menang.\n",
      "#YNWA #aaauuuwww ht…\n",
      " - @utdfocusid Belegug, ngitung jumlah titel juara liga Inggris selalu dari perubahan nama liga. ...siga bolon wae😅\n",
      " - Liverpool Kunci Juara Liga Inggris usai Hajar Tottenham Hotspur 5-1\n",
      "\n",
      "Cakeeeppp\n",
      " - RT @arsenalskitchen: Selamat, Liverpool. Juara Liga Inggris 2024/2025.\n",
      "\n",
      "Konsisten itu selalu krusial. Liverpool yg paling punya aspek itu s…\n",
      " - RT @panditfootball: Wataru Endo jadi samurai keempat yang juara Liga Inggris 🇯🇵\n",
      "\n",
      "Siapa lagi pemain Jepang yang bakal juara di Inggris? 🤔 ht…\n",
      " - Liverpool Patahkan Prediksi Tak Dijagokan Juara Liga Inggris 2024/2025 https://t.co/IRptZXDsD4\n",
      " - Mentari menyapa juara liga inggris. Scouse is not england. Kepalkan tanganmu kawand✊✊. Sampai menang.\n",
      "#YNWA #aaauuuwww https://t.co/Jtku5yAdv3\n",
      " - RT @idextratime: ✅ RESMI : Arsenal kembali kalah tipis dalam perebutan gelar juara Liga Inggris.\n",
      "\n",
      "2023 : Runner-up \n",
      "2024 : Runner-up \n",
      "2025…\n",
      "\n",
      "45. Cluster: 'liskiataumi idextratime' (total: 6 tweet)\n",
      " - @DwiPrasetyaSan1 @Seiiraz @LaunchSatelite @liskiataumi @idextratime @footballontnt Hadiahnya juga banyakan liga inggris.apa lagi udah jelas Uefa dan para wasit...nya Kebanyakan bepihak ke tim spanyol\n",
      " - @LaunchSatelite @liskiataumi @idextratime @footballontnt Cenderung liga lain itu dapat dukungan buat main di eropa  seperti perubahan jadwal tanding.beda di inggris  yg udah pasti ,dan persaingan   antar tim atas tengah bawah gep nya ngak beda jauh,\n",
      " - @notfakboyyy @liskiataumi @idextratime @footballontnt musim ini enggak sih\n",
      "dari 12 tim yang masih main di kompetisi eropa 4 dari liga inggris\n",
      "dan musim depan ada kemungkinan inggris punya 6 wakil di liga champions kalau MU/Spurs juara europa\n",
      " - @Seiiraz @TohhirRadin @LaunchSatelite @liskiataumi @idextratime @footballontnt Liga spanyol pemilik terbanyak gelar juara eropa. Bukan cuman UCL. UEL juga, bahkan sejak 2006, final UCL/UEL aja kalau tim spanyol vs inggris aja menang tim spanyol\n",
      " - @liskiataumi @idextratime @footballontnt Kalo gua ambil kesimpulan dari kata2 lu berarti liga Inggris nih liga Entertainment dong, secara prestasi di Eropa pun masih ada liga2 lain yg lebih baik faktanya\n",
      " - @TohhirRadin @LaunchSatelite @liskiataumi @idextratime @footballontnt Prestasi juara liga champion atau Europa, kalo dilihat banyak tim liga Inggris ko yang juara dibanding liga2 lain contoh Spain yang juara champions paling madrid barca liga Inggris nothingham sama Aston aja pernah\n",
      "\n",
      "46. Cluster: 'idextratime footballontnt' (total: 9 tweet)\n",
      " - @idextratime @footballontnt Liga lain mainya bisa 70 %  bisa sambil leha lehe bisa tetap menang.kalau di inggris main kaya gitu bisa  kalah lawan tim papan bawah  SEKALIPUN.\n",
      " - @DwiPrasetyaSan1 @Seiiraz @LaunchSatelite @liskiataumi @idextratime @footballontnt Hadiahnya juga banyakan liga inggris.apa lagi udah jelas Uefa dan para wasit...nya Kebanyakan bepihak ke tim spanyol\n",
      " - @LaunchSatelite @liskiataumi @idextratime @footballontnt Cenderung liga lain itu dapat dukungan buat main di eropa  seperti perubahan jadwal tanding.beda di inggris  yg udah pasti ,dan persaingan   antar tim atas tengah bawah gep nya ngak beda jauh,\n",
      " - @notfakboyyy @liskiataumi @idextratime @footballontnt musim ini enggak sih\n",
      "dari 12 tim yang masih main di kompetisi eropa 4 dari liga inggris\n",
      "dan musim depan ada kemungkinan inggris punya 6 wakil di liga champions kalau MU/Spurs juara europa\n",
      " - @idextratime @footballontnt Liga inggris media nya bagus dan liga nya di kelola dengan cara terbaik di dunia\n",
      "\n",
      "Ya meski tidak berimpact signifikan terhadap timnas nya, tetapi liga inggris terbaik dari pengelolaan dan penggunaan media\n",
      " - @Seiiraz @TohhirRadin @LaunchSatelite @liskiataumi @idextratime @footballontnt Liga spanyol pemilik terbanyak gelar juara eropa. Bukan cuman UCL. UEL juga, bahkan sejak 2006, final UCL/UEL aja kalau tim spanyol vs inggris aja menang tim spanyol\n",
      " - @liskiataumi @idextratime @footballontnt Kalo gua ambil kesimpulan dari kata2 lu berarti liga Inggris nih liga Entertainment dong, secara prestasi di Eropa pun masih ada liga2 lain yg lebih baik faktanya\n",
      " - @idextratime @footballontnt predikat liga terbaik sih masih bisa diperdebatkan. tapi yang pasti liga inggris ini liga terseru untuk diikuti. apalagi jam tayangnya bersahabat untuk asia. kalau nonton liga lain gak tau kenapa bawaannya bosen ditonton.\n",
      " - @TohhirRadin @LaunchSatelite @liskiataumi @idextratime @footballontnt Prestasi juara liga champion atau Europa, kalo dilihat banyak tim liga Inggris ko yang juara dibanding liga2 lain contoh Spain yang juara champions paling madrid barca liga Inggris nothingham sama Aston aja pernah\n",
      "\n",
      "47. Cluster: 'liskiataumi idextratime footballontnt' (total: 6 tweet)\n",
      " - @DwiPrasetyaSan1 @Seiiraz @LaunchSatelite @liskiataumi @idextratime @footballontnt Hadiahnya juga banyakan liga inggris.apa lagi udah jelas Uefa dan para wasit...nya Kebanyakan bepihak ke tim spanyol\n",
      " - @LaunchSatelite @liskiataumi @idextratime @footballontnt Cenderung liga lain itu dapat dukungan buat main di eropa  seperti perubahan jadwal tanding.beda di inggris  yg udah pasti ,dan persaingan   antar tim atas tengah bawah gep nya ngak beda jauh,\n",
      " - @notfakboyyy @liskiataumi @idextratime @footballontnt musim ini enggak sih\n",
      "dari 12 tim yang masih main di kompetisi eropa 4 dari liga inggris\n",
      "dan musim depan ada kemungkinan inggris punya 6 wakil di liga champions kalau MU/Spurs juara europa\n",
      " - @Seiiraz @TohhirRadin @LaunchSatelite @liskiataumi @idextratime @footballontnt Liga spanyol pemilik terbanyak gelar juara eropa. Bukan cuman UCL. UEL juga, bahkan sejak 2006, final UCL/UEL aja kalau tim spanyol vs inggris aja menang tim spanyol\n",
      " - @liskiataumi @idextratime @footballontnt Kalo gua ambil kesimpulan dari kata2 lu berarti liga Inggris nih liga Entertainment dong, secara prestasi di Eropa pun masih ada liga2 lain yg lebih baik faktanya\n",
      " - @TohhirRadin @LaunchSatelite @liskiataumi @idextratime @footballontnt Prestasi juara liga champion atau Europa, kalo dilihat banyak tim liga Inggris ko yang juara dibanding liga2 lain contoh Spain yang juara champions paling madrid barca liga Inggris nothingham sama Aston aja pernah\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "<>:15: SyntaxWarning: invalid escape sequence '\\S'\n",
      "<>:16: SyntaxWarning: invalid escape sequence '\\s'\n",
      "<>:15: SyntaxWarning: invalid escape sequence '\\S'\n",
      "<>:16: SyntaxWarning: invalid escape sequence '\\s'\n",
      "C:\\Users\\ASUS\\AppData\\Local\\Temp\\ipykernel_9268\\3075132213.py:15: SyntaxWarning: invalid escape sequence '\\S'\n",
      "  text = re.sub(\"http\\S+\", \"\", text)           # hapus link\n",
      "C:\\Users\\ASUS\\AppData\\Local\\Temp\\ipykernel_9268\\3075132213.py:16: SyntaxWarning: invalid escape sequence '\\s'\n",
      "  text = re.sub(\"[^a-zA-Z\\s]\", \"\", text)        # hapus simbol\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import re\n",
    "from collections import defaultdict\n",
    "from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory\n",
    "\n",
    "\n",
    "df = pd.read_csv('C:/kelompok1_22230011.csv')\n",
    "tweets = df['Isi Tweet'].dropna().tolist()\n",
    "\n",
    "\n",
    "factory = StopWordRemoverFactory()\n",
    "stop_words = set(factory.get_stop_words())\n",
    "\n",
    "def preprocess(text):\n",
    "    text = re.sub(\"http\\S+\", \"\", text)           # hapus link\n",
    "    text = re.sub(\"[^a-zA-Z\\s]\", \"\", text)        # hapus simbol\n",
    "    text = text.lower()\n",
    "    tokens = text.split()\n",
    "    return ' '.join([w for w in tokens if w not in stop_words])\n",
    "\n",
    "tweets_cleaned = [preprocess(t) for t in tweets]\n",
    "\n",
    "\n",
    "\n",
    "def extract_phrases(text, min_words=2, max_words=4):\n",
    "    words = text.split()\n",
    "    phrases = []\n",
    "    for size in range(min_words, max_words + 1):\n",
    "        for i in range(len(words) - size + 1):\n",
    "            phrase = ' '.join(words[i:i+size])\n",
    "            phrases.append(phrase)\n",
    "    return phrases\n",
    "\n",
    "\n",
    "phrase_to_docs = defaultdict(set)\n",
    "for idx, text in enumerate(tweets_cleaned):\n",
    "    phrases = extract_phrases(text)\n",
    "    for phrase in phrases:\n",
    "        phrase_to_docs[phrase].add(idx)\n",
    "\n",
    "min_docs_per_cluster = 5  \n",
    "common_phrases = {\n",
    "    phrase: docs for phrase, docs in phrase_to_docs.items()\n",
    "    if len(docs) >= min_docs_per_cluster\n",
    "}\n",
    "\n",
    "\n",
    "clusters = defaultdict(set)\n",
    "for phrase, docs in common_phrases.items():\n",
    "    clusters[f\"Cluster: '{phrase}'\"] = docs\n",
    "\n",
    "\n",
    "if not clusters:\n",
    "    print(\"Tidak ada cluster yang memenuhi ambang batas !!!!!\")\n",
    "else:\n",
    "    for i, (cluster_name, doc_ids) in enumerate(clusters.items(), start=1):\n",
    "        print(f\"\\n{i}. {cluster_name} (total: {len(doc_ids)} tweet)\")\n",
    "        for doc_id in doc_ids:\n",
    "            print(f\" - {tweets[doc_id]}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "f79ed40b-667e-48fa-a790-b1fe1a8968e5",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "<>:15: SyntaxWarning: invalid escape sequence '\\S'\n",
      "<>:16: SyntaxWarning: invalid escape sequence '\\s'\n",
      "<>:15: SyntaxWarning: invalid escape sequence '\\S'\n",
      "<>:16: SyntaxWarning: invalid escape sequence '\\s'\n",
      "C:\\Users\\ASUS\\AppData\\Local\\Temp\\ipykernel_9268\\166329454.py:15: SyntaxWarning: invalid escape sequence '\\S'\n",
      "  text = re.sub(\"http\\S+\", \"\", text)\n",
      "C:\\Users\\ASUS\\AppData\\Local\\Temp\\ipykernel_9268\\166329454.py:16: SyntaxWarning: invalid escape sequence '\\s'\n",
      "  text = re.sub(\"[^a-zA-Z\\s]\", \"\", text)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Hasil clustering telah disimpan ke hasil_cluster.csv\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import re\n",
    "from collections import defaultdict\n",
    "from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory\n",
    "\n",
    "\n",
    "df = pd.read_csv('C:/kelompok1_22230011.csv')\n",
    "tweets = df['Isi Tweet'].dropna().tolist()\n",
    "\n",
    "\n",
    "factory = StopWordRemoverFactory()\n",
    "stop_words = set(factory.get_stop_words())\n",
    "\n",
    "def preprocess(text):\n",
    "    text = re.sub(\"http\\S+\", \"\", text)          \n",
    "    text = re.sub(\"[^a-zA-Z\\s]\", \"\", text)        \n",
    "    text = text.lower()\n",
    "    tokens = text.split()\n",
    "    return ' '.join([w for w in tokens if w not in stop_words])\n",
    "\n",
    "tweets_cleaned = [preprocess(t) for t in tweets]\n",
    "\n",
    "\n",
    "def extract_phrases(text, min_words=2, max_words=4):\n",
    "    words = text.split()\n",
    "    phrases = []\n",
    "    for size in range(min_words, max_words + 1):\n",
    "        for i in range(len(words) - size + 1):\n",
    "            phrase = ' '.join(words[i:i+size])\n",
    "            phrases.append(phrase)\n",
    "    return phrases\n",
    "\n",
    "\n",
    "phrase_to_docs = defaultdict(set)\n",
    "for idx, text in enumerate(tweets_cleaned):\n",
    "    phrases = extract_phrases(text)\n",
    "    for phrase in phrases:\n",
    "        phrase_to_docs[phrase].add(idx)\n",
    "\n",
    "min_docs_per_cluster = 5  \n",
    "common_phrases = {\n",
    "    phrase: docs for phrase, docs in phrase_to_docs.items()\n",
    "    if len(docs) >= min_docs_per_cluster\n",
    "}\n",
    "\n",
    "\n",
    "clusters = defaultdict(set)\n",
    "for phrase, docs in common_phrases.items():\n",
    "    clusters[f\"Cluster: '{phrase}'\"] = docs\n",
    "\n",
    "\n",
    "import csv\n",
    "\n",
    "if not clusters:\n",
    "    print(\"Tidak ada cluster yang memenuhi ambang batas !!!!!\")\n",
    "else:\n",
    "    \n",
    "    rows = []\n",
    "    for i, (cluster_name, doc_ids) in enumerate(clusters.items(), start=1):\n",
    "        for doc_id in doc_ids:\n",
    "            rows.append({\n",
    "                \"Cluster\": cluster_name,\n",
    "                \"Tweet\": tweets[doc_id]\n",
    "            })\n",
    "   \n",
    "    df_out = pd.DataFrame(rows)\n",
    "    df_out.to_csv(\"hasil_cluster_22230011csv\", index=False, encoding=\"utf-8-sig\")\n",
    "    print(\"Hasil clustering telah disimpan ke hasil_cluster.csv\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1ef61064-aad1-444c-92ce-762933ca879c",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
